name = "strivetrack-media-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "42facf58740cfbdb2600673dd5ca4665"

# R2 binding (must exist in your CF account)
r2_buckets = [
  { binding = "R2_BUCKET", bucket_name = "strivetrack-media" }
]

d1_databases = [
  { binding = "DB", database_name = "strivetrack_d1", database_id = "REPLACE_WITH_D1_ID" }
]

[vars]
# These will be set via `wrangler secret put` in deployment
